name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: oxsecurity/megalinter/flavors/java@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: pull_request
          APPLY_FIXES_MODE: commit
          VALIDATE_ALL_CODEBASE: false
          SARIF_REPORTER: true

          LLM_ADVISOR_ENABLED: true
          LLM_PROVIDER: openai  # openai, anthropic, google, huggingface, mistral, deepseek, grok, ollama
          LLM_MODEL_NAME: openrouter/auto
          LLM_MAX_TOKENS: 1000
          LLM_TEMPERATURE: 0.1
          OPENAI_BASE_URL: https://openrouter.ai/api/v1
          OPENAI_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: 'megalinter-reports/megalinter-report.sarif'

  debug-builds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6 # zizmor: ignore[cache-poisoning]
        with:
          gradle-version: wrapper
          cache-provider: enhanced
          cache-read-only: false
          add-job-summary: on-failure
          validate-wrappers: true

      - name: Build APK
        run: ./gradlew assembleFullDebug

      - name: Upload APK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4 # zizmor: ignore[artipacked]
        with:
          name: app
          path: app/build/outputs/apk/full/debug/*.apk
