name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"
  push:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: wrapper
          cache-provider: enhanced
          cache-read-only: false
          add-job-summary: on-failure
          validate-wrappers: true

      - name: Build APK
        run: ./gradlew assembleFullDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/full/debug/*.apk
